api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
            pagination_enabled: true
            pagination_client_enabled: true
            pagination_client_items_per_page: true
            items_per_page: 10
            page_parameter_name: page
            items_per_page_parameter_name: itemsPerPage
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/merge-patch+json', 'application/json' ]
