nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_credentials: true
        allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
        allow_headers: ['Content-Type','Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
