nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
        allow_headers: ['Content-Type','Authorization','Accept']
        expose_headers: ['Link','Location','Content-Location']
        max_age: 3600
    paths:
        '^/': ~
