version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d symfony || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  php:
    build:
      context: ./php
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  composer:
    image: composer:2
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
    entrypoint: ["composer"]

  nginx:
    image: nginx:stable
    depends_on:
      php:
        condition: service_started
    volumes:
      - ../backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: ["8080:80"]
    restart: unless-stopped

  node:
    image: node:20
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports: ["5173:5173"]
    command: ["sh","-lc","[ -d node_modules ] || (npm ci || npm i); npm run dev -- --host --port 5173"]
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on:
      php:
        condition: service_started
      nginx:
        condition: service_started
    restart: unless-stopped

volumes:
  db_data: {}